### Variables that likely need to be adjusted ###

# root directory of databases (or where they will be downloaded if they don't exist yet)
REF_DB_ROOT_DIR:
    "/home/mdlee4/ref-dbs/"    

### Safer not to adjust these unless needed/wanted ###

KOFAMSCAN_DIR:
    "kofamscan_db"
CAT_DIR:
    "CAT_prepare_20200618"
GTDB_DATA_PATH:
    "GTDB-tk-ref-db"
CHECKM_DIR:
    "checkm-db"
